spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/"
    name: "postgres"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "postgres"

  servlet:
    multipart:
      max-file-size: "5MB"
      max-request-size: "5MB"

jwt:
  expireSecs: 604800
  secret: "asdts9g874wh54lwnODGDhdslghndass7gs42t3983y"
